# New upload keystore for Google Play Console (SHA1: 52:98:49:86:C3:A4:F8:59:97:02:5A:DD:9D:7C:FC:FA:4D:91:8A:EB)
# Created for upload key reset on 2025-07-08
storePassword=keymatch123
keyPassword=keymatch123
keyAlias=upload
storeFile=new-upload-keystore.jks
